# Generated by Django 4.1 on 2023-06-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inigramapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
