# Generated by Django 4.1 on 2023-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inigramapp', '0008_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
